# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'BEEJAN_RIDE'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'BEEJAN_RIDE'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  BEEJAN_RIDE:
    # Config indicated by + and applies to all files under models/example/
    staging:
      #+schema: staging 
      +materialized: view
    intermediate:
      #+schema: intermediate
      +materialized: view
    marts:
      #+schema: mart
      +materialized: table
      finance:
          +tags: ["finance"]
          #+schema: finance
      operations:
          +tags: ["operations"]
          #+schema: operations
      fraud:
          +tags: ["fraud"]
          #+schema: fraud

    
